length check test
charmgreen/SimilarityChecker-3567 pull request #1
Opened 2024-07-03 23:35 UTC by charmgreen

- 글자 수 검사(max 60점)
같은 글자 수 일때, 최대 점수 60점 획득
문자열 길이가 2배 이상 차이나면 0점
그 외에는 부분점수 획득

2024-07-03 23:56 UTC, yjyjy131 requested changes
else, else if 구문 로직을 따로 빼서 정리하면 더 가독성이 좋아질 것 같습니다!

2024-07-03 23:57 UTC, m1nqm1nq commented on StringSimilarity_KATA/similar.cpp
> +			return 60;
제 코드에서도 적용하지는 않았던 내용이지만....
60, 0 등의 magic number를 const int로 처리하면 어떨까합니다.
ex) LENGTH_SCORE_MAX, LENGTH_SCORE_MIN

2024-07-04 00:27 UTC, m1nqm1nq approved these changes
변경점 확인했습니다. 반영 감사합니다.

2024-07-04 00:36 UTC, yjyjy131 approved these changes
코드가 더 깔끔해진 것 같아요~

2024-07-04 00:40 UTC, merged